require File.join(File.dirname(__FILE__), 'acts_as_xapian', 'base'     )
require File.join(File.dirname(__FILE__), 'acts_as_xapian', 'query_base'     )
require File.join(File.dirname(__FILE__), 'acts_as_xapian', 'search'         )
require File.join(File.dirname(__FILE__), 'acts_as_xapian', 'similar'        )
require File.join(File.dirname(__FILE__), 'acts_as_xapian', 'core_ext/array' )